# https://docs.github.com/en/actions/quickstart

name: check-17ch.cn

# Controls when the workflow will run
on:
  push:
    tags-ignore:
      - *
  schedule:
  - cron: "0 9 * * 1"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Do check
        run: ./cli.sh 17ch.cn --days 90 'https://api.telegram.org/bot${{secrets.BOT_TOKEN}}/sendMessage?chat_id=-1001200878342&parse_mode=Markdown' -d 'text=请注意, $CHECK_CERT_HOST 的 HTTPS 证书将于 *$CHECK_CERT_DAYS* 天后过期！'
